### ISSUE TITLE
Add stale-if-error header

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/canonicalwebteam.flask-base#41]
We sometimes get transitory issues with API backends being unavailable, e.g. [here](https://github.com/canonical-web-and-design/upptime/issues/55).

We should probably set a stale-if-error header by default that is some relatively short time, just to protect users from seeing short-lived issues.

I guess stale-if-error should always be longer than max-age. But how long? 5 minutes?

**Comment by SirSamTumless** [comment]
Could you please give this a priority and estimate it?

**Comment by nottrobin** [comment]
this is not done
